### ISSUE TITLE
Legacy CMAA 2 produces less artifacts

### ISSUE THREAD

**Issue by 0CCULTIST** [LordOfLunacy/Insane-Shaders#10]
e55031ecf29b23186c3da9f1cbf5e9a31832554a
![image](https://github.com/user-attachments/assets/aa46b773-2eb3-4153-b2f6-aca7e1bb5bab)
d69305ca9b0429d4d1b180ff77554f43730ac38e
![image](https://github.com/user-attachments/assets/376c19b3-8675-4d8b-bf57-84efd37697cb)

I haven't updated CMAA 2 in awhile but after doing so I immediately noticed more artifacts in text and a visual comparison confirms this. The 2023 version has _less frequent_ "acne" in text as well as being much less _severe_ overall. In particular, the bottom parts of rounded characters such as "d", "e", & "a" have consistent acne, which isn't a problem on the old version. The large "A" has staircasing artifacts, again, not pressent on the older version.

**I have not confirmed which exact commit has caused this issue, just that it doesn't exist in the last 2023 version**

**Comment by jfouquart** [comment]
Hi, I can't test reshade in OpenGL ( my card is too old and doesn't support OpenGL 4.3 :( ), but I may have a fix, can you test with this version: https://github.com/jfouquart/Insane-Shaders/blob/master/Shaders/CMAA_2.fx ?

**Comment by jfouquart** [comment]
After reading many documentations, I think this, is the good fix.

**Comment by LordOfLunacy** [comment]
Got around to looking at it, I think you are correct. It's just the offset not being accurate for OpenGL. Can you create a PR with this change?

**Comment by jfouquart** [comment]
In fact after reading the D3D10 doc, I realized that D3D9 is the exception. So I updated my dev accordingly.

PS: It also has a little bonus, I found a way to optimize the size of the SimpleBlend LUT texture. If it's okay with you I'll include it in the PR.

**Comment by LordOfLunacy** [comment]
Let's do the fix first and have the optimization as a separate PR. (Incase that breaks something else)

**Comment by 0CCULTIST** [comment]
Would like to re-open this as now CMAA2 is much less effective at actually anti-aliasing compared to the old version, and there still are some artifacts
New version:
![image](https://github.com/user-attachments/assets/1b4d795c-e2ab-491d-916f-8fab5cf0354d)
Old version:
![image](https://github.com/user-attachments/assets/a7b02414-b26a-4758-baaf-6a5dcf13bc6d)
Draw attention to the hanging lamp in particular, the iron guard wire is blurrier in the new version, has more aliasing, and some slight acne (No, it's not due to the slight darkness difference in the image from the strobe of the light bulb)
Both versions at default settings & I've ensured the textures are up to date. MLAA edge detection doesn't significantly impact the issues I've shown.
This game is running in DX11.

**Comment by jfouquart** [comment]
Have you taken a look at https://github.com/LordOfLunacy/Insane-Shaders/issues/13#issuecomment-2484781195 ?

**Comment by 0CCULTIST** [comment]
> Have you taken a look at [#13 (comment)](https://github.com/LordOfLunacy/Insane-Shaders/issues/13#issuecomment-2484781195) ?

This has completely fixed it!

**Comment by jfouquart** [comment]
And with this change is there a regression with the previous game?

**Comment by jfouquart** [comment]
@0CCULTIST up ?

**Comment by 0CCULTIST** [comment]
> @0CCULTIST up ?

There's no regression in OpenGL. It seems to be fixed there too.
