### ISSUE TITLE
Failed to compile ... CMAA_2.fx (ReShade 6.3.3 Addon)

### ISSUE THREAD

**Issue by GT500org** [LordOfLunacy/Insane-Shaders#8]
I just installed ReShade with a variety of shaders including CMAA_2.fx and VRS_Map.fx from Insane Shaders for the new Project Borealis game. CMAA2 failed to compile with the following error messages in the log:

```
15:08:31:534 [24904] | ERROR | Failed to compile 'C:\Program Files (x86)\Steam\steamapps\common\Project Borealis\Windows\ProjectBorealis\Binaries\Win64\reshade-shaders\Shaders\Insane-Shaders\CMAA_2.fx':
C:\Program Files (x86)\Steam\steamapps\common\Project Borealis\Windows\ProjectBorealis\Binaries\Win64\reshade-shaders\Shaders\Insane-Shaders\CMAA_2.fx(659, 31): error X3004: undeclared identifier 'sSimpleShapeBlendVal'
C:\Program Files (x86)\Steam\steamapps\common\Project Borealis\Windows\ProjectBorealis\Binaries\Win64\reshade-shaders\Shaders\Insane-Shaders\CMAA_2.fx(771, 27): error X3004: undeclared identifier 'sZShapeScores'
```

This happened earlier today in another game with almost the same shaders installed. Shader configuration should be default, as it is a fresh install. OS is Windows 10 22H2.

Full log:
[ReShade.log](https://github.com/user-attachments/files/17707871/ReShade.log)

**Comment by LordOfLunacy** [comment]
There was a recent performance improvement implemented using a LUT texture for CMAA2, those are required for the shader. If you install those textures and place them in the texture folder, this issue should go away. (The texture is only used by dx9 atm, however it's loaded in irrespective of that)

**Comment by GT500org** [comment]
I guess ReShade's installer hasn't been updated to install the new texture yet? Is the list of shaders and dependencies hardcoded in the installer, or does it download them (meaning can I expect it to be updated at some point or will I have to manually install this texture for each game until a new version of ReShade releases)?

**Comment by GT500org** [comment]
Is the texture you're talking about `CMAA2SimpleShapeBlendValSharp.png`? I already have that in the "Textures" folder:

![explorer_ngOeGB8Hsz](https://github.com/user-attachments/assets/b4975ae3-ae2c-4d03-84e2-3d855cfb9e8f)

**Comment by jfouquart** [comment]
Sorry for the inconvenience, it's due to my latest modifications this PR should correct the problem.

**Comment by GT500org** [comment]
Fixed. Thanks.
